services:
  postgres:
    image: postgres:17
    container_name: mosud-postgres
    environment:
      POSTGRES_DB: olist
      POSTGRES_USER: student
      POSTGRES_PASSWORD: student
    ports:
      - "5432:5432"
    volumes:
      - mosud_pgdata:/var/lib/postgresql/data
      - ./data:/data

volumes:
  mosud_pgdata: